Part 1
mariaa-ea/Machine-learning-for-scientific-data-analysis pull request #1
Opened 2024-02-10 16:56 UTC by mariaa-ea

In processes.

2024-02-10 21:43 UTC, mariaa-ea commented
Интересен момент со стратификацией:
```python
X = data[['TRADEDATE','OPEN', 'HIGH', 'LOW']]
y = data['CLOSE']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, stratify=y,
                                                    random_state=random_state)
X_train.head()
```
Выдает ошибку:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-79-d71c181548e3>](https://localhost:8080/#) in <cell line: 4>()
      2 y = data['CLOSE']
      3 
----> 4 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, stratify=y,
      5                                                     random_state=random_state)
      6 X_train.head()

2 frames
[/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py](https://localhost:8080/#) in _iter_indices(self, X, y, groups)
   2076         class_counts = np.bincount(y_indices)
   2077         if np.min(class_counts) < 2:
-> 2078             raise ValueError(
   2079                 "The least populated class in y has only 1"
   2080                 " member, which is too few. The minimum"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```
Как с ней бороться?

Помню, как-то удавалось обойти, но не очень простыми путями...

P.s. или скрин:
![image](https://github.com/mariaa-ea/Machine-learning-for-scientific-data-analysis/assets/115352379/dc85e634-44e7-4d44-b1e4-b2d2dea969e2)

2024-02-14 21:26 UTC, mariaa-ea commented
Наличие хорошего скора при обучении модели линейной регрессии обусловлено мультиколлинеарностью - линейной корреляцией всех выбранных признаков.  
В следующих итерациях попробую исправить

2024-02-14 23:03 UTC, mariaa-ea commented
Хотелось бы узнать, с какими все-таки признаками стоит планировать свою дальнейшую работу?
Или они выбраны верно?

2024-02-19 20:17 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! Ответила в moodle!

2024-02-20 19:16 UTC, merged